name = "flowapp"
main = "src/index.ts"
compatibility_date = "2026-01-20"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
ALLOWED_ORIGINS    = "https://metroredec.github.io"
ENTRA_TENANT_ID    = "480bd49c-6f89-4faa-b39e-c7728d95d130"
ENTRA_CLIENT_ID    = "66130291-fc50-43f1-943c-6818dac1ba99"
ENTRA_API_AUDIENCE = "api://66130291-fc50-43f1-943c-6818dac1ba99"
PLATFORM_URL       = "https://flowapp.dbermeo.workers.dev"
APP_ENV            = "development"

[[d1_databases]]
binding       = "DB"
database_name = "flowapp-db"
database_id   = "f53d9fe8-d1bd-4348-8b70-1ce299b5f247"

[[r2_buckets]]
binding     = "FILES"
bucket_name = "flowapp-files"

[[kv_namespaces]]
binding = "KV"
id      = "095661415d644f4b924b8f11173896f0"

[env.production]
workers_dev = false


[env.production.vars]
ALLOWED_ORIGINS    = "https://metroredec.github.io"
ENTRA_TENANT_ID    = "480bd49c-6f89-4faa-b39e-c7728d95d130"
ENTRA_CLIENT_ID    = "66130291-fc50-43f1-943c-6818dac1ba99"
ENTRA_API_AUDIENCE = "api://66130291-fc50-43f1-943c-6818dac1ba99"
PLATFORM_URL       = "https://metroredec.github.io/flowapp"
APP_ENV            = "production"

[[env.production.d1_databases]]
binding       = "DB"
database_name = "flowapp-db"
database_id   = "f53d9fe8-d1bd-4348-8b70-1ce299b5f247"

[[env.production.r2_buckets]]
binding     = "FILES"
bucket_name = "flowapp-files"

[[env.production.kv_namespaces]]
binding = "KV"
id      = "095661415d644f4b924b8f11173896f0"
